projects:
  TS GraphQL:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: 5e6whs6odbhmfhghfa5mprp2sq
        maxDepth: 2
extensions:
  amplify:
    version: 3
